services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_SERVER_GIT_URI: "${CONFIG_SERVER_GIT_URI:-}"
      CONFIG_SERVER_GIT_USERNAME: "${CONFIG_SERVER_GIT_USERNAME:-}"
      CONFIG_SERVER_GIT_PASSWORD: "${CONFIG_SERVER_GIT_PASSWORD:-}"
      CONFIG_SERVER_CLONE_ON_START: "${CONFIG_SERVER_CLONE_ON_START:-true}"
      CONFIG_SERVER_FORCE_PULL: "${CONFIG_SERVER_FORCE_PULL:-true}"
      BASE_DIR: "${BASE_DIR:-/app/data}"
      CONFIG_SERVER_SEARCH_PATHS: "${CONFIG_SERVER_SEARCH_PATHS:-}"
      CONFIG_SERVER_DEFAULT_LABEL: "${CONFIG_SERVER_DEFAULT_LABEL:-main}"
      CONFIG_SERVER_GIT_TIMEOUT: "${CONFIG_SERVER_GIT_TIMEOUT:-3000}"
      CONFIG_SERVER_SKIP_SSL_VALIDATION: "${CONFIG_SERVER_SKIP_SSL_VALIDATION:-false}"
      CONFIG_SERVER_IGNORE_LOCAL_SSH: "${CONFIG_SERVER_IGNORE_LOCAL_SSH:-false}"
      CONFIG_SERVER_ALLOW_OVERRIDE: "${CONFIG_SERVER_ALLOW_OVERRIDE:-true}"
      CONFIG_SERVER_OVERRIDE_NONE: "${CONFIG_SERVER_OVERRIDE_NONE:-false}"
      CONFIG_SERVER_OVERRIDE_SYSTEM_PROPERTIES: "${CONFIG_SERVER_OVERRIDE_SYSTEM_PROPERTIES:-true}"
      JAVA_OPTS: "${JAVA_OPTS:--Xmx256m -XX:+UseG1GC}"
    ports:
      - "8080:8080"
    volumes:
      - ./data/config-server:/app/data