FROM openjdk:17-jdk

VOLUME /tmp
WORKDIR /app/data

COPY target/*.jar /app/app.jar

ENV CONFIG_SERVER_GIT_URI=${CONFIG_SERVER_GIT_URI}
ENV CONFIG_SERVER_GIT_USERNAME=${CONFIG_SERVER_GIT_USERNAME}
ENV CONFIG_SERVER_GIT_PASSWORD=${CONFIG_SERVER_GIT_PASSWORD}
ENV BASE_DIR=/app/data

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
