FROM openjdk:17-jdk

VOLUME /tmp
WORKDIR /app/data

COPY target/*.jar /app/app.jar

ENV CONFIG_SERVER_GIT_URI=
ENV CONFIG_SERVER_GIT_USERNAME=
ENV CONFIG_SERVER_GIT_PASSWORD=
ENV CONFIG_SERVER_CLONE_ON_START=true
ENV CONFIG_SERVER_FORCE_PULL=true
ENV BASE_DIR=/app/data
ENV CONFIG_SERVER_SEARCH_PATHS=""
ENV CONFIG_SERVER_DEFAULT_LABEL=main
ENV CONFIG_SERVER_GIT_TIMEOUT=3000
ENV CONFIG_SERVER_SKIP_SSL_VALIDATION=false
ENV CONFIG_SERVER_IGNORE_LOCAL_SSH=false
ENV CONFIG_SERVER_ALLOW_OVERRIDE=true
ENV CONFIG_SERVER_OVERRIDE_NONE=false
ENV CONFIG_SERVER_OVERRIDE_SYSTEM_PROPERTIES=true
ENV PORT=8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
