FROM openjdk:17-jdk

VOLUME /tmp
WORKDIR /app/data

COPY target/*.jar /app/app.jar

ARG CONFIG_SERVER_GIT_URI
ARG CONFIG_SERVER_GIT_USERNAME
ARG CONFIG_SERVER_GIT_PASSWORD
ARG CONFIG_SERVER_CLONE_ON_START=true
ARG CONFIG_SERVER_FORCE_PULL=true
ARG CONFIG_SERVER_SEARCH_PATHS=""
ARG CONFIG_SERVER_DEFAULT_LABEL=main
ARG CONFIG_SERVER_GIT_TIMEOUT=3000
ARG CONFIG_SERVER_SKIP_SSL_VALIDATION=false
ARG CONFIG_SERVER_IGNORE_LOCAL_SSH=false
ARG CONFIG_SERVER_ALLOW_OVERRIDE=true
ARG CONFIG_SERVER_OVERRIDE_NONE=false
ARG CONFIG_SERVER_OVERRIDE_SYSTEM_PROPERTIES=true
ARG PORT=8080

ENV CONFIG_SERVER_GIT_URI=${CONFIG_SERVER_GIT_URI}
ENV CONFIG_SERVER_GIT_USERNAME=${CONFIG_SERVER_GIT_USERNAME}
ENV CONFIG_SERVER_GIT_PASSWORD=${CONFIG_SERVER_GIT_PASSWORD}
ENV CONFIG_SERVER_CLONE_ON_START=${CONFIG_SERVER_CLONE_ON_START}
ENV CONFIG_SERVER_FORCE_PULL=${CONFIG_SERVER_FORCE_PULL}
ENV CONFIG_SERVER_SEARCH_PATHS=${CONFIG_SERVER_SEARCH_PATHS}
ENV CONFIG_SERVER_DEFAULT_LABEL=${CONFIG_SERVER_DEFAULT_LABEL}
ENV CONFIG_SERVER_GIT_TIMEOUT=${CONFIG_SERVER_GIT_TIMEOUT}
ENV CONFIG_SERVER_SKIP_SSL_VALIDATION=${CONFIG_SERVER_SKIP_SSL_VALIDATION}
ENV CONFIG_SERVER_IGNORE_LOCAL_SSH=${CONFIG_SERVER_IGNORE_LOCAL_SSH}
ENV CONFIG_SERVER_ALLOW_OVERRIDE=${CONFIG_SERVER_ALLOW_OVERRIDE}
ENV CONFIG_SERVER_OVERRIDE_NONE=${CONFIG_SERVER_OVERRIDE_NONE}
ENV CONFIG_SERVER_OVERRIDE_SYSTEM_PROPERTIES=${CONFIG_SERVER_OVERRIDE_SYSTEM_PROPERTIES}
ENV PORT=${PORT}

ENV JAVA_OPTS="-Xmx256m -XX:+UseG1GC"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
