spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URI}
          username: ${CONFIG_SERVER_GIT_USERNAME}
          password: ${CONFIG_SERVER_GIT_PASSWORD}
          clone-on-start: true
          force-pull: true
          basedir: ${BASE_DIR}
server:
  port: ${PORT:8080}

